import sys
from numpy import *

def writeoutput(argumen,z,num_nodes,nodes,num_elements_bulk,elements_bulk,displ,strain,stress):
	
	vtkfile_ini = open(argumen+'_out.'+str(z+1)+'.vtk','w')
	vtkfile_ini.write('# vtk DataFile Version 2.0\n')
	vtkfile_ini.write('Generated with Solid Solver\n')
	vtkfile_ini.write('ASCII\n')
	vtkfile_ini.write('DATASET UNSTRUCTURED_GRID\n')
	vtkfile_ini.write('POINTS')
	vtkfile_ini.write(' ')
	vtkfile_ini.write(str(num_nodes))
	vtkfile_ini.write(' ')
	vtkfile_ini.write('float \n')
	for i in range(num_nodes):
		vtkfile_ini.write(str(nodes[i][1]))
		vtkfile_ini.write(' ')
		vtkfile_ini.write(str(nodes[i][2]))
		vtkfile_ini.write(' ')
		vtkfile_ini.write(str(nodes[i][3]))
		vtkfile_ini.write('\n')	
	vtkfile_ini.write('CELLS')
	vtkfile_ini.write(' ')
	vtkfile_ini.write(str(num_elements_bulk))
	vtkfile_ini.write(' ')
	vtkfile_ini.write(str(num_elements_bulk*4))
	vtkfile_ini.write('\n')
	for i in range(num_elements_bulk):
		vtkfile_ini.write('3')
		vtkfile_ini.write(' ')
		vtkfile_ini.write(str(int(elements_bulk[i][5])-1))
		vtkfile_ini.write(' ')
		vtkfile_ini.write(str(int(elements_bulk[i][6])-1))
		vtkfile_ini.write(' ')	
		vtkfile_ini.write(str(int(elements_bulk[i][7])-1))
		vtkfile_ini.write('\n')	
	vtkfile_ini.write('CELL_TYPES')
	vtkfile_ini.write(' ')
	vtkfile_ini.write(str(num_elements_bulk))
	vtkfile_ini.write('\n')
	for i in range(num_elements_bulk):
		vtkfile_ini.write('5 \n')
	vtkfile_ini.write('POINT_DATA')
	vtkfile_ini.write(' ')
	vtkfile_ini.write(str(num_nodes))
	vtkfile_ini.write('\n')
	vtkfile_ini.write('VECTORS')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('Displacement')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('float\n')
	for i in range(num_nodes):
		vtkfile_ini.write(str(displ[2*i]))
		vtkfile_ini.write(' ')
		vtkfile_ini.write(str(displ[(2*i)+1]))
		vtkfile_ini.write(' ')
		vtkfile_ini.write('0')
		vtkfile_ini.write('\n')	
	vtkfile_ini.write('SCALARS')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('EPSXX')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('float\n')
	vtkfile_ini.write('LOOKUP_TABLE')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('default\n')
	for i in range(num_nodes):
		vtkfile_ini.write(str(strain[0][i]))
		vtkfile_ini.write('\n')	
	vtkfile_ini.write('SCALARS')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('EPSYY')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('float\n')
	vtkfile_ini.write('LOOKUP_TABLE')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('default\n')
	for i in range(num_nodes):
		vtkfile_ini.write(str(strain[1][i]))
		vtkfile_ini.write('\n')
	vtkfile_ini.write('SCALARS')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('EPSXY')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('float\n')
	vtkfile_ini.write('LOOKUP_TABLE')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('default\n')
	for i in range(num_nodes):
		vtkfile_ini.write(str(strain[2][i]))
		vtkfile_ini.write('\n')	
	vtkfile_ini.write('SCALARS')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('SIGXX')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('float\n')
	vtkfile_ini.write('LOOKUP_TABLE')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('default\n')
	for i in range(num_nodes):
		vtkfile_ini.write(str(stress[0][i]))
		vtkfile_ini.write('\n')	
	vtkfile_ini.write('SCALARS')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('SIGYY')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('float\n')
	vtkfile_ini.write('LOOKUP_TABLE')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('default\n')
	for i in range(num_nodes):
		vtkfile_ini.write(str(stress[1][i]))
		vtkfile_ini.write('\n')
	vtkfile_ini.write('SCALARS')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('SIGXY')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('float\n')
	vtkfile_ini.write('LOOKUP_TABLE')
	vtkfile_ini.write(' ')
	vtkfile_ini.write('default\n')
	for i in range(num_nodes):
		vtkfile_ini.write(str(stress[2][i]))
		vtkfile_ini.write('\n')	
	vtkfile_ini.close()
